
class AllPrograme{
    public static void main(String... s){
        Pattern1.main();
		System.out.println();
        Pattern2.main();
		System.out.println();
        Pattern3.main();
		System.out.println();
        Pattern4.main();
		System.out.println();
        Pattern5.main();
		System.out.println();
        Pattern6.main();
		System.out.println();
        Pattern7.main();
		System.out.println();
        Pattern8.main();
		System.out.println();
        Pattern9.main();
		System.out.println();
        Pattern10.main();
		System.out.println();
        Pattern11.main();
		System.out.println();
        Pattern12.main();
		System.out.println();
        Pattern13.main();
		System.out.println();
        Pattern14.main();
		System.out.println();
        Pattern15.main();
		System.out.println();
        Pattern16.main();
		System.out.println();
        Pattern17.main();
		System.out.println();
        Pattern18.main();
		System.out.println();
        Pattern19.main();
		System.out.println();
        Pattern20.main();
    }
}
